# -*- coding: utf-8 -*-
"""BERT_SQuAD_Question_Answering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSLz-22pb6KHkSPUj2cFBNmfVhI48pqd
"""

!pip install -q transformers datasets evaluate accelerate

import torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForQuestionAnswering
from transformers import TrainingArguments, Trainer
import evaluate
import collections
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

dataset = load_dataset("squad")

print(dataset)
print(dataset["train"][0])

model_checkpoint = "bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
model = AutoModelForQuestionAnswering.from_pretrained(model_checkpoint).to(device)

max_length = 384
stride = 128

def preprocess_training_examples(examples):
    questions = [q.strip() for q in examples["question"]]

    inputs = tokenizer(
        questions,
        examples["context"],
        max_length=max_length,
        truncation="only_second",
        stride=stride,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length",
    )

    offset_mapping = inputs.pop("offset_mapping")
    sample_map = inputs.pop("overflow_to_sample_mapping")
    answers = examples["answers"]

    start_positions = []
    end_positions = []

    for i, offsets in enumerate(offset_mapping):
        sample_idx = sample_map[i]
        answer = answers[sample_idx]

        start_char = answer["answer_start"][0]
        end_char = start_char + len(answer["text"][0])

        sequence_ids = inputs.sequence_ids(i)

        context_start = 0
        while sequence_ids[context_start] != 1:
            context_start += 1

        context_end = len(sequence_ids) - 1
        while sequence_ids[context_end] != 1:
            context_end -= 1

        if offsets[context_start][0] > start_char or offsets[context_end][1] < end_char:
            start_positions.append(0)
            end_positions.append(0)
        else:
            idx = context_start
            while idx <= context_end and offsets[idx][0] <= start_char:
                idx += 1
            start_positions.append(idx - 1)

            idx = context_end
            while idx >= context_start and offsets[idx][1] >= end_char:
                idx -= 1
            end_positions.append(idx + 1)

    inputs["start_positions"] = start_positions
    inputs["end_positions"] = end_positions

    return inputs

train_dataset = dataset["train"].select(range(40000))
validation_dataset = dataset["validation"].select(range(3000))
tokenized_train = train_dataset.map(
    preprocess_training_examples,
    batched=True,
    remove_columns=train_dataset.column_names
)

print(tokenized_train)

training_args = TrainingArguments(
    output_dir="./bert-squad-results-clean",
    eval_strategy="no",
    save_strategy="no",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=100,
    fp16=True,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train
)

trainer.train()

def preprocess_validation_examples(examples):
    questions = [q.strip() for q in examples["question"]]

    inputs = tokenizer(
        questions,
        examples["context"],
        max_length=max_length,
        truncation="only_second",
        stride=stride,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length",
    )

    sample_map = inputs.pop("overflow_to_sample_mapping")
    example_ids = []

    for i in range(len(inputs["input_ids"])):
        sample_idx = sample_map[i]
        example_ids.append(examples["id"][sample_idx])

        sequence_ids = inputs.sequence_ids(i)
        offsets = inputs["offset_mapping"][i]

        inputs["offset_mapping"][i] = [
            offset if sequence_ids[k] == 1 else None
            for k, offset in enumerate(offsets)
        ]

    inputs["example_id"] = example_ids
    return inputs

tokenized_validation = validation_dataset.map(
    preprocess_validation_examples,
    batched=True,
    remove_columns=validation_dataset.column_names
)

print(tokenized_validation)

raw_predictions = trainer.predict(tokenized_validation)

start_logits, end_logits = raw_predictions.predictions

print(start_logits.shape)
print(end_logits.shape)

metric = evaluate.load("squad")

n_best = 20
max_answer_length = 30

examples = validation_dataset
features = tokenized_validation

example_to_features = collections.defaultdict(list)

for idx, feature in enumerate(features):
    example_to_features[feature["example_id"]].append(idx)

predicted_answers = []

for example in examples:
    example_id = example["id"]
    context = example["context"]
    answers = []

    for feature_index in example_to_features[example_id]:
        start_logit = start_logits[feature_index]
        end_logit = end_logits[feature_index]
        offsets = features[feature_index]["offset_mapping"]

        start_indexes = np.argsort(start_logit)[-1 : -n_best - 1 : -1].tolist()
        end_indexes = np.argsort(end_logit)[-1 : -n_best - 1 : -1].tolist()

        for start_index in start_indexes:
            for end_index in end_indexes:
                if offsets[start_index] is None or offsets[end_index] is None:
                    continue

                if end_index < start_index:
                    continue

                if end_index - start_index + 1 > max_answer_length:
                    continue

                start_char = offsets[start_index][0]
                end_char = offsets[end_index][1]

                answer_text = context[start_char:end_char]
                score = start_logit[start_index] + end_logit[end_index]

                answers.append({
                    "text": answer_text,
                    "logit_score": score
                })

    if len(answers) > 0:
        best_answer = max(answers, key=lambda x: x["logit_score"])
        predicted_answers.append({
            "id": example_id,
            "prediction_text": best_answer["text"]
        })
    else:
        predicted_answers.append({
            "id": example_id,
            "prediction_text": ""
        })

theoretical_answers = [
    {
        "id": ex["id"],
        "answers": ex["answers"]
    }
    for ex in examples
]

results = metric.compute(
    predictions=predicted_answers,
    references=theoretical_answers
)

results

from transformers import pipeline
import torch
model = model.to(device)
qa_pipeline = pipeline(
    "question-answering",
    model=model,
    tokenizer=tokenizer,
    device=0 if torch.cuda.is_available() else -1
)

context = """
The Eiffel Tower is located in Paris, France.
It was completed in 1889 and is one of the most famous landmarks in the world.
"""

question = "Where is the Eiffel Tower located?"

result = qa_pipeline(question=question, context=context)

print("Question:", question)
print("Answer:", result["answer"])
print("Confidence:", result["score"])

for i in range(5):
    ex = validation_dataset[i]

    result = qa_pipeline(
        question=ex["question"],
        context=ex["context"]
    )

    print("=" * 80)
    print("Question:", ex["question"])
    print("Correct answer:", ex["answers"]["text"][0])
    print("Model answer:", result["answer"])
    print("Confidence:", result["score"])

import ipywidgets as widgets
import math
from IPython.display import display, clear_output
context_box = widgets.Textarea(
    value="""The Eiffel Tower is located in Paris, France. It was completed in 1889 and is one of the most famous landmarks in the world.""",
    placeholder="Paste your paragraph here...",
    description="Paragraph:",
    layout=widgets.Layout(width="100%", height="180px")
)

questions_box = widgets.Textarea(
    value="""Where is the Eiffel Tower located?
When was the Eiffel Tower completed?
What is one of the most famous landmarks in the world?""",
    placeholder="Write one question per line...",
    description="Questions:",
    layout=widgets.Layout(width="100%", height="120px")
)

run_button = widgets.Button(
    description="Get Answers",
    button_style="success"
)

output_area = widgets.Output()

def answer_questions(button):
    with output_area:
        clear_output()

        context = context_box.value.strip()
        questions = [q.strip() for q in questions_box.value.split("\n") if q.strip()]

        if not context:
            print("Please enter a paragraph.")
            return

        if not questions:
            print("Please enter at least one question.")
            return

        for i, question in enumerate(questions, 1):
            result = qa_pipeline(question=question, context=context)

            raw_score = float(result["score"])
            display_score = 1 / (1 + math.exp(-raw_score))

            print("=" * 80)
            print(f"Question {i}: {question}")
            print(f"Answer: {result['answer']}")

            print(f"Confidence: {display_score:.4f}")

run_button.on_click(answer_questions)

display(context_box, questions_box, run_button, output_area)

from google.colab import drive
drive.mount('/content/drive')

model.save_pretrained("/content/drive/MyDrive/bert_qa_model_40k")
tokenizer.save_pretrained("/content/drive/MyDrive/bert_qa_model_40k")

from transformers import AutoModelForQuestionAnswering, AutoTokenizer, pipeline
import torch
model_path = "/content/drive/MyDrive/bert_qa_model_40k"
model = AutoModelForQuestionAnswering.from_pretrained(model_path).to(device)
tokenizer = AutoTokenizer.from_pretrained(model_path)
qa_pipeline = pipeline(
    "question-answering",
    model=model,
    tokenizer=tokenizer,
    device=0 if torch.cuda.is_available() else -1
)

import matplotlib.pyplot as plt

models = [
    "DistilBERT\n20k",
    "BERT\n20k",
    "BERT\n40k"
]

em_scores = [68.15, 73.25, 76.20]
f1_scores = [76.42, 81.61, 84.39]

x = range(len(models))

plt.figure(figsize=(8,5))

plt.plot(x, em_scores, marker='o', label='Exact Match (EM)')
plt.plot(x, f1_scores, marker='o', label='F1 Score')

plt.xticks(x, models)
plt.ylabel("Score")
plt.xlabel("Model")
plt.title("Model Performance Comparison")

plt.legend()
plt.grid(True)

plt.savefig("model_performance_comparison.png", bbox_inches='tight')

plt.show()